import './globals.css'
import { Inter } from 'next/font/google'
import logo from '../Assets/albumpickslogo.png';
const inter = Inter({ subsets: ['latin'] })
import Image from 'next/image';
import Nav from './Components/Nav';
import { getServerSession } from 'next-auth/next';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const session =  getServerSession();

  return (

    <html lang="en">
     
      <body className={inter.className} user={session?.user} >
     
        <Nav/>
        {children}
        
        
        </body>
    </html>
  )
}
